title: Casper's SECURITY LAB
subtitle: Cybersecurity, Web Development, Robotics & Experiments
description: Cybersecurity, CTF, Web Development, Robotics, IoT
keywords: 資安, CTF, Web, Robotics, IoT
author: Casper
language: en
timezone: Asia/Taipei

url: https://casper3790.github.io/casper.tw
root: /casper.tw/

theme: landscape

deploy:
  type: git
  repo: https://github.com/casper3790/casper.tw.git
  branch: gh-pages

feed:
  type: atom
  path: feed.xml
  limit: 20

sitemap:
  path: sitemap.xml
